### ISSUE TITLE
Get merger tree for prototype galaxy in Illustris

### ISSUE THREAD

**Issue by astronomyk** [astronomyk/illustris_elt#1]
### Tasks for week of 14.10.2019

- [] Look for a couple of interesting galaxies
  - [] Elliptical
  - [] Spiral
  - [] Failed galaxy - (Globular cluster, LMC-type tiny spiral, etc)

- [] Pull out merger tree for each for the galaxies
  - Get sub_halo_id number for each snapshot

- [] Data about snapshots
  - Redshift of each snapshot
  - Corresponding distance of each snapshot
